# Generated by Django 6.0.2 on 2026-05-31 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_product_wishlist_wishlist'),
        ('shopkeeper', '0011_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopkeeper.product'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
