# Generated by Django 6.0.2 on 2026-04-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0008_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.CharField(default='not added yet'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='not added yet'),
        ),
    ]
