# Generated by Django 6.0.2 on 2026-02-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='login_as',
            field=models.BooleanField(default=False),
        ),
    ]
