# Generated by Django 6.0.2 on 2026-02-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_userprofile_login_as'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='login_as',
            field=models.CharField(choices=[('customer', 'Customer'), ('shopkeeper', 'Shopkeeper')], default='customer', max_length=20),
        ),
    ]
